### ISSUE TITLE
Is there to find difference percentage of two images??

### ISSUE THREAD

**Issue by viveksrinivasanss** [bevacqua/image-diff-2#1]
Hi Bevacqua,

Your library is really excellent to use because of it simplicity in approach.My question is actually not an issue on the other hand just a clarification.
Instead of getting a difference between two images as a image.Is there a way I can get it as a percentage of difference (a numerical). So that It will be easy for comparison and to quantify how much a image is different from other.

**Comment by viveksrinivasanss** [comment]
Added the above feature. Please merge the pull request #2

**Comment by bevacqua** [comment]
Merged
